<?php

$a = 1+1;
$a = 1-1;
$a = 1/1;
$a = 1*1;
$a = 1%1;
$a = 1^1;
$a = true  and  false;
$a = true  or   false;
$a = true  xor  false;
$a = true&&false;
$a = true||false;
$a = 00|11;
$a = 00&11;
$a = 00^11;
$a = 1=== 2;
$a = 1== 2;
$a = 1<> 2;
$a = 1!= 2;
$a = 2!== 2;
$a = 1>2;
$a = 1<2;
$a = 1>>2;
$a = 1<<2;
$a = $a /* bla*/  < $b;
$a = 1
    +    2
    +   3    +
    4;
$a = 'hel'
    .    'lo';